// <auto-generated />
using System;
using Labb3_RestApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb3_RestApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230506081040_Blorp")]
    partial class Blorp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb3_RestApi.Models.Interest", b =>
                {
                    b.Property<int>("InterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterestId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FKPerson")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InterestId");

                    b.HasIndex("FKPerson");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            InterestId = 1,
                            Description = "Ultimate competition combined of all martial arts in the world",
                            FKPerson = 1,
                            Title = "MMA"
                        },
                        new
                        {
                            InterestId = 2,
                            Description = "There is plethora of games that i like, but i prefer competetive once",
                            FKPerson = 1,
                            Title = "Gaming"
                        },
                        new
                        {
                            InterestId = 3,
                            Description = "Coding holds a huge intrest considering its my potential future",
                            FKPerson = 1,
                            Title = "Muaythai"
                        },
                        new
                        {
                            InterestId = 4,
                            Description = "Reality shows are very fun because i like to see drama",
                            FKPerson = 2,
                            Title = "RealityShows"
                        },
                        new
                        {
                            InterestId = 5,
                            Description = "Killing younglings for the good of the future",
                            FKPerson = 3,
                            Title = "DarkSide"
                        },
                        new
                        {
                            InterestId = 6,
                            Description = "I like rebellions and kissing siblings",
                            FKPerson = 4,
                            Title = "Rebellions"
                        },
                        new
                        {
                            InterestId = 7,
                            Description = "Star constelations are beautiful",
                            FKPerson = 2,
                            Title = "Stargazing"
                        });
                });

            modelBuilder.Entity("Labb3_RestApi.Models.Links", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LinkId"));

                    b.Property<int?>("FKPersonId")
                        .HasColumnType("int");

                    b.Property<int?>("FKinterestId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LinkId");

                    b.HasIndex("FKPersonId");

                    b.HasIndex("FKinterestId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            LinkId = 1,
                            FKPersonId = 1,
                            FKinterestId = 1,
                            Title = "MMA clip",
                            URL = "https://www.youtube.com/watch?v=LNySNc76NNU"
                        },
                        new
                        {
                            LinkId = 2,
                            FKPersonId = 2,
                            FKinterestId = 2,
                            Title = "Gaming",
                            URL = "https://eu.shop.battle.net/en-gb?from=root"
                        },
                        new
                        {
                            LinkId = 3,
                            FKPersonId = 3,
                            FKinterestId = 3,
                            Title = "Muaythai",
                            URL = "https://www.facebook.com/Drakstadenmuaythai/?locale=sv_SE"
                        },
                        new
                        {
                            LinkId = 4,
                            FKPersonId = 4,
                            FKinterestId = 4,
                            Title = "RealityShows",
                            URL = ""
                        },
                        new
                        {
                            LinkId = 5,
                            FKPersonId = 1,
                            FKinterestId = 3,
                            Title = "",
                            URL = ""
                        },
                        new
                        {
                            LinkId = 6,
                            FKPersonId = 1,
                            FKinterestId = 5,
                            Title = "DarkSide",
                            URL = "https://www.youtube.com/watch?v=Ogcd-etnFLw"
                        },
                        new
                        {
                            LinkId = 7,
                            FKPersonId = 2,
                            FKinterestId = 7,
                            Title = "Rebellions",
                            URL = "https://www.youtube.com/watch?v=m8drjLtX1Wc"
                        },
                        new
                        {
                            LinkId = 8,
                            FKPersonId = 4,
                            FKinterestId = 6,
                            Title = "Rebellion",
                            URL = "https://www.youtube.com/watch?v=Ogcd-etnFLw"
                        });
                });

            modelBuilder.Entity("Labb3_RestApi.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            FirstName = "Oskar",
                            LastName = "Åhling",
                            Phone = "070-2138149"
                        },
                        new
                        {
                            PersonId = 2,
                            FirstName = "Ina",
                            LastName = "Nilsson",
                            Phone = "074-2251267"
                        },
                        new
                        {
                            PersonId = 3,
                            FirstName = "Anakin",
                            LastName = "Skywalker",
                            Phone = "076-7643267"
                        },
                        new
                        {
                            PersonId = 4,
                            FirstName = "Leia",
                            LastName = "Solo",
                            Phone = "072-1234567"
                        });
                });

            modelBuilder.Entity("Labb3_RestApi.Models.Interest", b =>
                {
                    b.HasOne("Labb3_RestApi.Models.Person", "person")
                        .WithMany()
                        .HasForeignKey("FKPerson");

                    b.Navigation("person");
                });

            modelBuilder.Entity("Labb3_RestApi.Models.Links", b =>
                {
                    b.HasOne("Labb3_RestApi.Models.Person", "person")
                        .WithMany()
                        .HasForeignKey("FKPersonId");

                    b.HasOne("Labb3_RestApi.Models.Interest", "interest")
                        .WithMany()
                        .HasForeignKey("FKinterestId");

                    b.Navigation("interest");

                    b.Navigation("person");
                });
#pragma warning restore 612, 618
        }
    }
}
